### ISSUE TITLE
Project topic brainstorming

### ISSUE THREAD

**Issue by Staneesh** [Staneesh/Repro2023#1]
Let's figure out what our project should be. I think it would be the easiest to find a relatively recent research paper that published a git repo along with the actual paper. R implementations are usually brief - we could rewrite it in python and try to reproduce their results that way. 

What do you think about it? Do we have some other ideas? What should our area of research be?

**Comment by afoster28** [comment]
That would be interesting or we could find something written in Python and focus on replicating it, as one of the key concerns here is simply whether the same analysis can be reproduced at a later stage. I suspect more information will be shared soon.

Either way, areas of interest include investment strategies, financial pricing models and econometrics.

**Comment by Staneesh** [comment]
Ok so we're not coding an RPG game I see ;-;

Can we try finding some cool papers over the weekend? We should focus on that regardless of the final assignment requirements.

**Comment by ibaranochnikov** [comment]
I have found an interesting paper, the results of which we could try to reproduce: http://www.ripublication.com/ijaer19/ijaerv14n3_08.pdf

In short, authors try to forecast AirPassengers time series using the ARIMA model and present error metrics of this approach. What do you think?

**Comment by Staneesh** [comment]
I think we decided on the project topic a while ago already. Closing 🌴 😄
